spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  data:
    mongodb:
      authentication-database: lottor
      database: lottor
      host: localhost
      port: ${MONGO_PORT:27017}

lottor:
  redis:
    cluster: false
#      redirects: 20
    hostName: localhost
    port: 6379
  manager:
    netty:
      port: 9998
      serialize: kryo
      maxConnection: 100
      maxThreads: 16
      delayTime: 5
      heartTime: 20
      checkPeriod: 60
      initDelay: 10

transactionWaitMaxTime: 500
redisSaveMaxTime: 3000

logging:
  level:
    root: info
    com.blueskykong.lottor.server: debug
  path: "./logs"

stream.content-type: application/x-java-object;type=com.blueskykong.lottor.common.entity.TransactionMsgAdapter
