spring:
  profiles:
    active: dev
  application:
      name: t-producer
  cloud:
    consul:
      host: localhost
      port: 8501
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
#        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: ${spring.cloud.consul.discovery.service-name}-${spring.profiles.active}-${spring.cloud.consul.discovery.ip-address}-${random.value}
        service-name: transaction-producer

server:
  port: 8009


management:
  health:
    defaults:
      enabled: false
  endpoint:
    shutdown:
      enabled: false
  security:
    enabled: false

logging:
  level:
    root: info
    com.blueskykong.tm.core: debug
  path: "./logs"

---
tx:
  enabled: true
  core:
    compensation-cache-type: redis
    tx-redis-config:
      host-name: localhost
      port: 6378
      password: pwd
    serializer: kryo
    netty-serializer: kryo
    blocking-queue-type: Linked
    compensation: true
    tx-manager-id: lotor