spring:
  application:
    name: tm-server
  cloud:
    consul:
      host: 192.168.1.204
      port: 8500
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: tm-server-${server.port}
        service-name: tm-server

server:
  port: 9666

management:
  security:
    enabled: false